BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    
]

blog/urls.py
from django.urls import path
from .views import UserRegisterView
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'blog'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Post

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        pass


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

blog/views.py
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm




class UserRegisterView(CreateView):
    form_class = UserCreationForm  
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login') 


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']  

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm  
    template_name = 'blog/post_form.html'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm 
    template_name = 'blog/post_form.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    success_url = reverse_lazy('post_list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
   {% block content %} 
   
   {%endblock content %}
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Hello welcome</h1>

{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="login-form">
    <h2>Login</h2>
    <form method="post">
      {% csrf_token %}
      {{ form }}
      <button class="submit-button" type="submit">Login</button>
    </form>
  </div>
{% endblock %}

blog/templates/blog/logout.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="logout-message">
    <h2>Logout</h2>
    <p>You have been logged out successfully.</p>
  </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>{{ post.title }}</h2>
  <p>{{ post.content }}</p>
  <p>Author: {{ post.author }}</p>
  <a href="{% url 'blog:post_edit' post.pk %}">Edit</a>
  <a href="{% url 'blog:post_delete' post.pk %}">Delete</a>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>{% if form.instance.pk %}Edit{% else %}Create{% endif %} Blog Post</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="submit-button" type="submit">Save</button>
  </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>All Blog Posts</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'blog:post_create' %}">Create New Post</a>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="register-form">
    <h2>Register</h2>
    <form method="post">
      {% csrf_token %}
      {{ form }}
      <button class="submit-button" type="submit">Register</button>
    </form>
  </div>
{% endblock %}